version: "3"
services:
  web:
    image: zzpp/video
    build:
      context: ./deploy
      dockerfile: dockerfile
    container_name: video
    ports:
      - 8003:8003
    volumes:
      - ./app:/video/app
    environment:
      TZ: Asia/Shanghai
    restart: unless-stopped
    depends_on:
      - nhf
  nhf:
    image: zzpp/nhf
    build:
      context: ../nginx-http-flv/deploy
      dockerfile: dockerfile
    container_name: nhf
    ports:
      - 1935:1935
      - 9000:9000
    restart: unless-stopped
