version: "3"
services:
  web:
    image: zzpp/video:v5
    container_name: video
    ports:
      - 8003:8003
    volumes:
      - ./app:/video/app
    environment:
      TZ: Asia/Shanghai
    restart: always
    depends_on:
      - nhf
  nhf:
    image: zzpp/nginx-http-flv:v6
    container_name: nhf
    ports:
      - 1935:1935
      - 9000:9000
    restart: always
