
server:
  port: 8003

ffmpeg:
  pixel: 640*360

live-url:
  ip: 127.0.0.1
  port: 9000
  application-name: videoMonitor

station-udp:
  communicate: true
  xa-ip: 192.168.140.240
  xa-port: 6662
  sy-ip: 123.0.0.1
  sy-port: 6662
  wh-ip: 124.0.0.1
  wh-port: 6662

camera:
  config-txt-win: D:\\work-code\\back\\video\\src\\main\\resources\\config\\camera.txt


yk:
  log-path: /video/app/logs
logging:
  pattern:
    file: "%d %-20level [%thread] %logger : %msg%n"
  file:
    name: ${yk.log-path}/${live-url.application-name}.log
    max-size: 10MB
    max-history: 10