FROM jrottenberg/ffmpeg:3.3-alpine

FROM openjdk:8
MAINTAINER zp

WORKDIR /video/app

COPY --from=0 / /
COPY hcnet /home/opt/hcnet
#COPY ../app/application.yml
#ADD ../app/*.jar video.jar

ENTRYPOINT ["java","-jar","video-0.0.1-SNAPSHOT.jar","--spring.config.location=application.yml"]

EXPOSE 8003

